AWSTemplateFormatVersion: 2010-09-09
Description: This template deploys a Virtual Private Network
Resources:
  UdacityVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: 'true'
      Tags:
      - Key: name
        Value: simontestvpc